@FocusNotes_Api_HostAddress = http://localhost:5062

###

GET {{FocusNotes_Api_HostAddress}}/User/1
Accept: application/json

###

POST {{FocusNotes_Api_HostAddress}}/User/
Content-Type: application/json
